# Generated by Django 4.0.3 on 2022-04-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='Value',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
