# Generated by Django 4.0.3 on 2022-04-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0003_alter_projeto_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='Risk',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=1),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='Value',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
